databases:
  - name: Budget-App
    databaseName: budget_app_02gt
    user: budget_app_02gt_user

services:
  - type: web
    name: Budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_02gt
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false